#ifndef ERRORS_H
#define ERRORS_H

typedef enum ErrorCode_e {
    OK = 0,
    ERR_ERROR = -1,
    ERR_NO_MEMORY = -2,
    ERR_DRIVER_NOT_INITIALIZED = -3,
    ERR_I2C_ERROR = -4,
    ERR_SENSOR_NOT_CONNECTED = -5,
    ERR_INVALID_PARAM = -6,
    ERR_DRIVER_ALREADY_INITIALIZED = -7,
    ERR_SCHEDULER_MAX_TASKS_REACHED = -8,
    ERR_SERVO_NOT_INITIALIZED = -9,
    ERR_SERVO_OUT_OF_BOUNDS = -10,
    ERR_SERVO_INVALID_CHANNEL = -11,
    ERR_MOTION_CONTROLLER_NOT_INITIALIZED = -12,
    ERR_INVALID_LEG_ID = -13,
    ERR_INVALID_JOINT_ID = -14,
} ErrorCode_e;

#endif  // !ERRORS_H
